### ISSUE TITLE
Generate Test Runs Based on YAML instead of represented suites in cucumber

### ISSUE THREAD

**Issue by dhakiki** [Originate/cucumber-testrail#6]
@kevgo brought up an interesting suggestion in the ART review today that generating test runs based on at least one scenario representation in cucumber may not give enough visibility. Perhaps then, the test runs are created based on the suites defined in the `cucumber_testrail.yml` file instead.. so the yml file: 

```
testRailUrl: 'https://rmsqa.testrail.net/index.php?'

suites:

  - suite:
      project_id: 1
      project_symbol: 'RM'
      suite_id: 1
      section_id: 10
      testplan_id: 64

  - suite:
      project_id: 2
      project_symbol: 'EM'
      suite_id: 1
      testplan_id: 85
```

would fetch all the cases and create test runs for the RM and the EM suite.

I like that better :)
